version: "3.8"
services:
  weather1:
    build: weather_service/
    ports:
      - 5001:${PORT}
    environment:
      - PORT=${PORT}
      - URL=${URL}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_SERVER=${REDIS_SERVER}
  weather2:
    build: weather_service/
    ports:
      - 5002:${PORT}
    environment:
      - PORT=${PORT}
      - URL=${URL}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_SERVER=${REDIS_SERVER}
  balancer:
    build: Load_balancer/
    ports:
        - 5000:5000         
    depends_on:
        - weather1
        - weather2
  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      # - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
  
  redis-1:
    image: redis
    container_name: redis-1
    ports:
      - ${REDIS_PORT}
    command: [ "redis-server", "--port ${REDIS_PORT}" ]

  redis-2:
    image: redis
    container_name: redis-2
    ports:
      - ${REDIS_PORT}
    command: [ "redis-server", "--port ${REDIS_PORT}" ]

  redis-3:
    image: redis
    container_name: redis-3
    ports:
      - ${REDIS_PORT}
    command: [ "redis-server", "--port ${REDIS_PORT}" , "--slaveof", "redis-1", "${REDIS_PORT}" ]

  redis-4:
    image: redis
    container_name: redis-4
    ports:
      - ${REDIS_PORT}
    command: [ "redis-server", "--port ${REDIS_PORT}" , "--slaveof", "redis-2", "${REDIS_PORT}" ]

  twem-proxy:
    image: tarantool/twemproxy
    command:
      - --verbose=11
    volumes:
      - ./nutcracker.yml:/conf/nutcracker.yml
    depends_on:
      - redis-1
      - redis-2
      - redis-3
      - redis-4
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}