version: "3.8"
services:
  weather1:
    build: weather_service/
    ports:
      - 5001:${PORT}
    environment:
      - PORT=${PORT}
      - URL=${URL}
  weather2:
    build: weather_service/
    ports:
      - 5002:${PORT}
    environment:
      - PORT=${PORT}
      - URL=${URL}
  balancer:
    build: Load_balancer/
    ports:
        - 5000:5000         
    depends_on:
        - weather1
        - weather2
  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      # - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090